name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  page:
    name: Build&Update pages
    if: true
    uses: ./.github/workflows/page.yml
  app:
    name: Build app
    uses: ./.github/workflows/app.yml

  release:
    needs: app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ./**/genish-impact*.*
          body_path: ./CHANGELOG.md
